### PR TITLE
Update open-terminal-here

### PR DESCRIPTION
**Pull request by kainonergon**
F4 doesn't work with thunar

### CODE REVIEW

**Comment by Chrysostomus** [comment]
It requires setting up custom action for thunar.

**Comment by kainonergon** [comment]
I have 'open terminal here' custom action for thunar, but it works only from menu. I couldn't find how to assign F4 to it.

**Comment by Chrysostomus** [comment]
I'll post a link when I have time

**Comment by kainonergon** [comment]
Thanks. I've found it. Edited `~/.config/Thunar/accels.scm` to add F4 shortcut.

**Pull request closed without merging**
